# Generated by Django 5.0.4 on 2024-05-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='todo',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Default Title', max_length=200, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(verbose_name='Задание'),
        ),
    ]
